services:
  - type: web
    name: truck-tracker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: META_WA_PHONE_NUMBER_ID
        sync: false
      - key: META_WA_ACCESS_TOKEN
        sync: false
      - key: META_VERIFY_TOKEN
        sync: false